policies = []

[[repositories]]
name = "juice-shop"
url = "https://github.com/juice-shop/juice-shop"

[schedule]
frequency = "daily"
time = "02:00"
timezone = "UTC"

[notifications]
enabled = true

[notifications.filters]
min_severity = "high"
# Temporarily set to false until persistent storage is implemented
only_new_vulnerabilities = false

# Discord webhook for security alerts
# IMPORTANT: Replace with your actual Discord webhook URL
[[notifications.webhooks]]
name = "Discord Security Channel"
# TODO: Replace YOUR_WEBHOOK_ID and YOUR_WEBHOOK_TOKEN with actual values
# Get these from Discord: Server Settings -> Integrations -> Webhooks -> Create Webhook
url = "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN"
webhook_type = "discord"
enabled = true

[storage]
database_path = "vulfy_automation.db"
retain_days = 30
export_format = "json"
export_path = "vulfy_exports"
